import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Common ─────────────────────────────────────────────────────────────
    'common.lang': 'العربية',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.saved': 'Saved!',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.share': 'Share',
    'common.export': 'Export',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.generate': 'Generate',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.search': 'Search your designs or inspiration...',
    'common.viewAll': 'View All',
    'common.copyright': '© 2025 Zabatly AI. All rights reserved.',
    'common.madeWith': 'Made with love for beautiful homes',

    // ── Navigation ─────────────────────────────────────────────────────────
    'nav.howItWorks': 'How it works',
    'nav.examples': 'Examples',
    'nav.pricing': 'Pricing',
    'nav.testimonials': 'Testimonials',
    'nav.login': 'Log In',
    'nav.getStarted': 'Get Started Free',
    'nav.home': 'Home',
    'nav.myDesigns': 'My Designs',
    'nav.moodBoards': 'Mood Boards',
    'nav.roomRedesign': 'Room Redesign',
    'nav.exploreStyles': 'Explore Styles',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.upgrade': 'Upgrade Now',
    'nav.proMember': 'Pro Member',
    'nav.proDesc': 'Unlock unlimited AI generations and HD exports.',

    // ── Footer ─────────────────────────────────────────────────────────────
    'footer.tagline': 'AI-powered interior design for every home.',
    'footer.platform': 'Platform',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.howItWorks': 'How it works',
    'footer.gallery': 'Gallery',
    'footer.styles': 'Styles',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.helpCenter': 'Help Center',
    'footer.api': 'API',
    'footer.community': 'Community',
    'footer.terms': 'Terms of Service',

    // ── Auth ───────────────────────────────────────────────────────────────
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Enter your details to access your studio.',
    'auth.login.email': 'Email Address',
    'auth.login.password': 'Password',
    'auth.login.forgot': 'Forgot Password?',
    'auth.login.submit': 'Sign In',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.signUp': 'Create Account',
    'auth.login.social': 'Or continue with',
    'auth.signup.title': 'Join Zabatly',
    'auth.signup.subtitle': 'Start your interior design journey today.',
    'auth.signup.name': 'Full Name',
    'auth.signup.role': 'I am a...',
    'auth.signup.homeowner': 'Homeowner',
    'auth.signup.designer': 'Interior Designer',
    'auth.signup.submit': 'Create Account',
    'auth.signup.hasAccount': 'Already have an account?',
    'auth.signup.login': 'Sign In',
    'auth.forgot.title': 'Reset Password',
    'auth.forgot.subtitle': "Enter your email and we'll send you a link.",
    'auth.forgot.submit': 'Send Reset Link',
    'auth.forgot.back': 'Back to Login',
    'auth.forgot.sent': "We've sent a reset link to",
    'auth.forgot.resend': 'Resend Email',
    'auth.reset.title': 'Set New Password',
    'auth.reset.subtitle': 'Choose a strong password for your account.',
    'auth.reset.password': 'New Password',
    'auth.reset.submit': 'Reset Password',
    'auth.reset.success': 'Password reset! You can now log in.',

    // ── Hero ───────────────────────────────────────────────────────────────
    'hero.badge': 'AI-Powered Design Studio',
    'hero.title': 'Design your home before you',
    'hero.titleAccent': 'furnish it.',
    'hero.titleAr': '(ظبط شقتك قبل ما تفرشها)',
    'hero.desc': 'Experience the future of interior design with AI-powered mood boards and room redesigns. Upload your room and let our AI create the perfect aesthetic in seconds.',
    'hero.cta': 'Start Designing Free',
    'hero.gallery': 'View Gallery',
    'hero.users': 'Joined by 2,000+ happy homeowners',
    'hero.aiRendering': 'AI Rendering',
    'hero.optimizing': 'Optimizing lighting... 75%',

    // ── Process ────────────────────────────────────────────────────────────
    'process.badge': 'The Process',
    'process.title': 'Three steps to your dream home',
    'process.step1.title': '1. Upload Photo',
    'process.step1.desc': 'Snap a picture of any room in its current state. Our AI handles empty spaces or fully furnished ones.',
    'process.step2.title': '2. Pick a Style',
    'process.step2.desc': 'Choose from curated styles like Modern, Japandi, Industrial, or Classic to match your vibe.',
    'process.step3.title': '3. AI Transformation',
    'process.step3.desc': 'Our AI generates photorealistic renders and a detailed shopping list tailored to your budget.',

    // ── Gallery ────────────────────────────────────────────────────────────
    'gallery.badge': 'Gallery',
    'gallery.title': 'Example AI Transformations',
    'gallery.styleLabel': 'Style',

    // ── Pricing ────────────────────────────────────────────────────────────
    'pricing.badge': 'Simple Pricing',
    'pricing.title': 'Choose your design plan',
    'pricing.subtitle': 'Start free. Upgrade when you need more. Cancel anytime.',
    'pricing.currency': 'EGP',
    'pricing.perMonth': '/month',
    'pricing.freeForever': 'Free forever',
    'pricing.mostPopular': 'Most Popular',
    'pricing.free.name': 'Free',
    'pricing.free.feat1': '2 mood boards',
    'pricing.free.feat2': '1 room redesign',
    'pricing.free.feat3': 'Watermarked exports',
    'pricing.free.feat4': 'HD quality',
    'pricing.free.feat5': 'Canvas editor',
    'pricing.basic.name': 'Basic',
    'pricing.basic.feat1': '10 mood boards / month',
    'pricing.basic.feat2': '5 room redesigns / month',
    'pricing.basic.feat3': 'HD exports (no watermark)',
    'pricing.basic.feat4': 'Canvas editor',
    'pricing.basic.feat5': 'Shareable links',
    'pricing.premium.name': 'Premium',
    'pricing.premium.feat1': 'Unlimited mood boards',
    'pricing.premium.feat2': 'Unlimited room redesigns',
    'pricing.premium.feat3': 'High-res exports (no watermark)',
    'pricing.premium.feat4': 'Priority AI generation',
    'pricing.premium.feat5': 'Canvas editor + sharing',
    'pricing.cta.free': 'Get Started Free',
    'pricing.cta.basic': 'Choose Basic',
    'pricing.cta.premium': 'Choose Premium',
    'pricing.cta.getStarted': 'Get Started',
    'pricing.cta.choosePro': 'Choose Pro',
    'pricing.cta.contact': 'Contact Sales',
    'pricing.payPerDesign': 'Or pay per design:',
    'pricing.ppBoard': 'per mood board',
    'pricing.ppRedesign': 'per room redesign',
    'pricing.paymentMethods': 'Payment Methods Accepted',
    'pricing.instapay': 'InstaPay',
    'pricing.vodafone': 'Vodafone Cash',
    'pricing.paymentNote': 'Upload your payment screenshot for instant AI verification.',
    'pricing.faq': 'How does payment work?',
    'pricing.faqDesc': 'After selecting a plan, transfer the amount via InstaPay or Vodafone Cash to our account, then upload a screenshot of your receipt. Our AI verifies it automatically within minutes.',

    // ── Testimonials ───────────────────────────────────────────────────────
    'testimonials.badge': 'Wall of Love',
    'testimonials.title': 'Loved by design enthusiasts',

    // ── CTA Section ────────────────────────────────────────────────────────
    'cta.title': 'Ready to transform your space?',
    'cta.desc': 'Join thousands of people who have already designed their dream homes with Zabatly. No credit card required.',
    'cta.button': 'Start Designing Now (ابدأ التصميم)',

    // ── Dashboard ─────────────────────────────────────────────────────────
    'dashboard.welcome': 'Welcome back,',
    'dashboard.welcomeAr': 'أهلاً بك',
    'dashboard.subtitle': "Your creative journey continues. What's the plan for today?",
    'dashboard.explore': 'Explore Trends',
    'dashboard.newMoodboard': 'New Mood Board',
    'dashboard.newRedesign': 'New Room Redesign',
    'dashboard.stat.active': 'Active Designs',
    'dashboard.stat.credits': 'AI Credits Remaining',
    'dashboard.stat.instant': 'Instant Redesign',
    'dashboard.stat.japandi': 'Try the new Japandi AI',
    'dashboard.stat.tryNow': 'Try Now',
    'dashboard.stat.thisWeek': '+3 this week',
    'dashboard.recent': 'Recent Projects',
    'dashboard.viewAll': 'View All',
    'dashboard.startNew': 'Start New Design',
    'dashboard.modifiedAgo': 'Modified',
    'dashboard.footer.privacy': 'Privacy Policy',
    'dashboard.footer.terms': 'Terms of Service',
    'dashboard.footer.support': 'Support Center',

    // ── Mood Board Generator ───────────────────────────────────────────────
    'moodboard.title': 'AI Mood Board Generator',
    'moodboard.subtitle': 'Describe your vision and let our AI create the perfect atmosphere.',
    'moodboard.params': 'Design Parameters',
    'moodboard.roomType': 'Room Type',
    'moodboard.room.living': 'Living Room',
    'moodboard.room.bedroom': 'Bedroom',
    'moodboard.room.kitchen': 'Kitchen',
    'moodboard.room.bathroom': 'Bathroom',
    'moodboard.room.office': 'Office',
    'moodboard.style': 'Design Style',
    'moodboard.style.modern': 'Modern Scandinavian',
    'moodboard.style.midcentury': 'Mid-Century Modern',
    'moodboard.style.industrial': 'Industrial Loft',
    'moodboard.style.boho': 'Bohemian Chic',
    'moodboard.style.minimal': 'Minimalist Zen',
    'moodboard.style.luxury': 'Luxe Art Deco',
    'moodboard.dominantColor': 'Dominant Color',
    'moodboard.promptLabel': 'Detailed Prompt (optional)',
    'moodboard.promptPlaceholder': 'e.g. A sun-drenched minimalist living room with oak textures and cream linen fabrics...',
    'moodboard.generateBtn': 'Generate Mood Board',
    'moodboard.generating': 'Generating...',
    'moodboard.mainConcept': 'Main Concept',
    'moodboard.palette': 'AI Generated Palette',
    'moodboard.materials': 'Material Library',
    'moodboard.exportPdf': 'Export PDF',
    'moodboard.shareLink': 'Share Link',
    'moodboard.saveToFav': 'Save to Favorites',
    'moodboard.saveDashboard': 'Save to Dashboard',

    // ── Room Redesign ──────────────────────────────────────────────────────
    'redesign.title': 'AI Room Redesign',
    'redesign.subtitle': 'Upload a photo of your current space and let our AI transform it in seconds.',
    'redesign.uploadTitle': 'Upload Your Photo',
    'redesign.uploadLabel': 'Drag & drop your room image here',
    'redesign.uploadSub': 'Supports JPG, PNG up to 10MB',
    'redesign.browse': 'Browse Files',
    'redesign.roomType': 'Room Type',
    'redesign.intensity': 'Style Intensity',
    'redesign.proTip': 'Pro Tip',
    'redesign.proTipText': 'Take photos from the corner of the room at chest height for the most accurate spatial perspective.',
    'redesign.preview': 'Interactive Preview',
    'redesign.before': 'Before',
    'redesign.after': 'After',
    'redesign.variations': 'AI Generated Variations',
    'redesign.regenerate': 'Regenerate All',
    'redesign.useStyle': 'Use This Style',
    'redesign.active': 'ACTIVE',
    'redesign.ctaTitle': 'Love this look?',
    'redesign.ctaDesc': 'Get the furniture list from this redesign delivered to your inbox.',
    'redesign.ctaEmail': 'Enter your email',
    'redesign.ctaBtn': 'Get List',
    'redesign.generating': 'Generating your redesign...',

    // ── Payment ────────────────────────────────────────────────────────────
    'payment.backToPricing': 'Back to Pricing',
    'payment.planSummary': 'Plan Summary',
    'payment.method': 'Payment Method',
    'payment.instapay': 'InstaPay',
    'payment.vodafone': 'Vodafone Cash',
    'payment.instantTransfer': 'Instant transfer',
    'payment.mobileWallet': 'Mobile wallet',
    'payment.instructions': 'Transfer Instructions',
    'payment.step1': 'Open your',
    'payment.step1App': 'app',
    'payment.step2': 'Transfer',
    'payment.step2To': 'to:',
    'payment.step3': 'Take a screenshot of the transfer receipt',
    'payment.step4': 'Upload the screenshot below',
    'payment.uploadTitle': 'Upload Payment Screenshot',
    'payment.uploadLabel': 'Drag & drop your receipt screenshot here',
    'payment.uploadSub': 'Supports JPG, PNG up to 10MB',
    'payment.verifyBtn': 'Verify Payment',
    'payment.processing': 'Processing...',
    'payment.verifying': 'Verifying your payment...',
    'payment.verifyingDesc': 'This usually takes less than a minute',
    'payment.successTitle': 'Subscription Activated!',
    'payment.successDesc': 'Your payment has been verified. You can now enjoy all the features of your plan.',
    'payment.goToDashboard': 'Go to Dashboard',
    'payment.failTitle': 'Payment verification failed',
    'payment.failDesc': 'Ensure the screenshot is clear and the amount is correct. If the issue persists, it will be reviewed manually.',
    'payment.manualTitle': 'Under Manual Review',
    'payment.manualDesc': "We couldn't automatically verify your payment. Our team will review it within 24 hours.",

    // ── Settings ───────────────────────────────────────────────────────────
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.saveChanges': 'Save Changes',
    'settings.subscription': 'Subscription',
    'settings.currentPlan': 'Current Plan',
    'settings.expires': 'Expires',
    'settings.active': 'Active',
    'settings.upgrade': 'Upgrade',
    'settings.usageThisMonth': 'Usage This Month',
    'settings.moodBoards': 'Mood Boards',
    'settings.redesigns': 'Room Redesigns',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.notif.payment': 'Payment confirmations',
    'settings.notif.expiry': 'Subscription expiry warnings',
    'settings.notif.tips': 'Design tips & inspiration',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteDesc': 'All your data will be permanently deleted. This cannot be undone.',
    'settings.deleteBtn': 'Delete My Account',

    // ── Editor ─────────────────────────────────────────────────────────────
    'editor.untitled': 'Untitled Mood Board',
    'editor.back': 'Back',
    'editor.save': 'Save',
    'editor.saved': 'Saved!',
    'editor.export': 'Export',
    'editor.share': 'Share',
    'editor.tools.select': 'Select',
    'editor.tools.text': 'Text',
    'editor.tools.image': 'Image',
    'editor.tools.shape': 'Shape',
    'editor.panel.images': 'Images',
    'editor.panel.colors': 'Colors',
    'editor.panel.layers': 'Layers',
    'editor.uploadImage': 'Upload image',
    'editor.moodBoardImages': 'Mood Board Images',
    'editor.palette': 'Color Palette',
    'editor.designColors': 'Design Colors',
  },

  ar: {
    // ── Common ─────────────────────────────────────────────────────────────
    'common.lang': 'English',
    'common.save': 'حفظ',
    'common.saving': 'جاري الحفظ...',
    'common.saved': 'تم الحفظ!',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.share': 'مشاركة',
    'common.export': 'تصدير',
    'common.download': 'تنزيل',
    'common.upload': 'رفع',
    'common.generate': 'توليد',
    'common.loading': 'جاري التحميل...',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.close': 'إغلاق',
    'common.search': 'ابحث في تصاميمك أو الإلهام...',
    'common.viewAll': 'عرض الكل',
    'common.copyright': '© ٢٠٢٥ ظبطلي AI. جميع الحقوق محفوظة.',
    'common.madeWith': 'صُنع بمحبة للمنازل الجميلة',

    // ── Navigation ─────────────────────────────────────────────────────────
    'nav.howItWorks': 'كيف يعمل',
    'nav.examples': 'أمثلة',
    'nav.pricing': 'الأسعار',
    'nav.testimonials': 'آراء العملاء',
    'nav.login': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ مجاناً',
    'nav.home': 'الرئيسية',
    'nav.myDesigns': 'تصاميمي',
    'nav.moodBoards': 'لوحات الأفكار',
    'nav.roomRedesign': 'إعادة تصميم الغرفة',
    'nav.exploreStyles': 'استكشاف الأنماط',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.upgrade': 'ترقية الآن',
    'nav.proMember': 'عضو برو',
    'nav.proDesc': 'افتح تصاميم غير محدودة وتصدير عالي الجودة.',

    // ── Footer ─────────────────────────────────────────────────────────────
    'footer.tagline': 'تصميم داخلي بالذكاء الاصطناعي لكل منزل.',
    'footer.platform': 'المنصة',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.howItWorks': 'كيف يعمل',
    'footer.gallery': 'المعرض',
    'footer.styles': 'الأنماط',
    'footer.aboutUs': 'من نحن',
    'footer.contact': 'تواصل معنا',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.helpCenter': 'مركز المساعدة',
    'footer.api': 'API',
    'footer.community': 'المجتمع',
    'footer.terms': 'شروط الخدمة',

    // ── Auth ───────────────────────────────────────────────────────────────
    'auth.login.title': 'مرحباً بعودتك',
    'auth.login.subtitle': 'أدخل بياناتك للوصول إلى الاستوديو الخاص بك.',
    'auth.login.email': 'البريد الإلكتروني',
    'auth.login.password': 'كلمة المرور',
    'auth.login.forgot': 'نسيت كلمة المرور؟',
    'auth.login.submit': 'تسجيل الدخول',
    'auth.login.noAccount': 'ليس لديك حساب؟',
    'auth.login.signUp': 'إنشاء حساب',
    'auth.login.social': 'أو المتابعة باستخدام',
    'auth.signup.title': 'انضم إلى ظبطلي',
    'auth.signup.subtitle': 'ابدأ رحلة التصميم الداخلي الخاصة بك اليوم.',
    'auth.signup.name': 'الاسم الكامل',
    'auth.signup.role': 'أنا...',
    'auth.signup.homeowner': 'صاحب منزل',
    'auth.signup.designer': 'مصمم داخلي',
    'auth.signup.submit': 'إنشاء حساب',
    'auth.signup.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signup.login': 'تسجيل الدخول',
    'auth.forgot.title': 'إعادة تعيين كلمة المرور',
    'auth.forgot.subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً.',
    'auth.forgot.submit': 'إرسال رابط الإعادة',
    'auth.forgot.back': 'العودة لتسجيل الدخول',
    'auth.forgot.sent': 'أرسلنا رابط إعادة التعيين إلى',
    'auth.forgot.resend': 'إعادة إرسال البريد',
    'auth.reset.title': 'تعيين كلمة مرور جديدة',
    'auth.reset.subtitle': 'اختر كلمة مرور قوية لحسابك.',
    'auth.reset.password': 'كلمة المرور الجديدة',
    'auth.reset.submit': 'تعيين كلمة المرور',
    'auth.reset.success': 'تم تعيين كلمة المرور! يمكنك الآن تسجيل الدخول.',

    // ── Hero ───────────────────────────────────────────────────────────────
    'hero.badge': 'استوديو تصميم مدعوم بالذكاء الاصطناعي',
    'hero.title': 'صمم منزلك قبل أن',
    'hero.titleAccent': 'تفرشه.',
    'hero.titleAr': '(ظبط شقتك قبل ما تفرشها)',
    'hero.desc': 'اختبر مستقبل التصميم الداخلي مع لوحات الأفكار وإعادة التصميم بالذكاء الاصطناعي. ارفع صورة غرفتك واترك ذكاءنا الاصطناعي ينشئ الجمال المثالي في ثوانٍ.',
    'hero.cta': 'ابدأ التصميم مجاناً',
    'hero.gallery': 'عرض المعرض',
    'hero.users': 'انضم إلينا أكثر من ٢٠٠٠ صاحب منزل سعيد',
    'hero.aiRendering': 'ذكاء اصطناعي',
    'hero.optimizing': 'تحسين الإضاءة... ٧٥٪',

    // ── Process ────────────────────────────────────────────────────────────
    'process.badge': 'العملية',
    'process.title': 'ثلاث خطوات لمنزل أحلامك',
    'process.step1.title': '١. ارفع الصورة',
    'process.step1.desc': 'التقط صورة لأي غرفة في حالتها الحالية. يتعامل ذكاؤنا الاصطناعي مع المساحات الفارغة أو المؤثثة بالكامل.',
    'process.step2.title': '٢. اختر النمط',
    'process.step2.desc': 'اختر من بين الأنماط المنسقة مثل المودرن، أو الياباندي، أو الصناعي، أو الكلاسيكي.',
    'process.step3.title': '٣. تحول الذكاء الاصطناعي',
    'process.step3.desc': 'ينشئ ذكاؤنا الاصطناعي صوراً واقعية وقائمة تسوق مفصلة تناسب ميزانيتك.',

    // ── Gallery ────────────────────────────────────────────────────────────
    'gallery.badge': 'المعرض',
    'gallery.title': 'أمثلة لتحولات الذكاء الاصطناعي',
    'gallery.styleLabel': 'نمط',

    // ── Pricing ────────────────────────────────────────────────────────────
    'pricing.badge': 'أسعار بسيطة',
    'pricing.title': 'اختر خطة التصميم الخاصة بك',
    'pricing.subtitle': 'ابدأ مجاناً. قم بالترقية عند الحاجة. ألغِ في أي وقت.',
    'pricing.currency': 'ج.م',
    'pricing.perMonth': '/شهرياً',
    'pricing.freeForever': 'مجاني للأبد',
    'pricing.mostPopular': 'الأكثر شيوعاً',
    'pricing.free.name': 'مجاني',
    'pricing.free.feat1': 'لوحتا أفكار',
    'pricing.free.feat2': 'إعادة تصميم واحدة',
    'pricing.free.feat3': 'تصدير بعلامة مائية',
    'pricing.free.feat4': 'جودة عالية',
    'pricing.free.feat5': 'محرر اللوحة',
    'pricing.basic.name': 'أساسي',
    'pricing.basic.feat1': '١٠ لوحات أفكار / شهرياً',
    'pricing.basic.feat2': '٥ إعادات تصميم / شهرياً',
    'pricing.basic.feat3': 'تصدير عالي الجودة (بدون علامة مائية)',
    'pricing.basic.feat4': 'محرر اللوحة',
    'pricing.basic.feat5': 'روابط مشاركة',
    'pricing.premium.name': 'مميز',
    'pricing.premium.feat1': 'لوحات أفكار غير محدودة',
    'pricing.premium.feat2': 'إعادة تصميم غير محدودة',
    'pricing.premium.feat3': 'تصدير عالي الدقة (بدون علامة مائية)',
    'pricing.premium.feat4': 'أولوية في توليد الذكاء الاصطناعي',
    'pricing.premium.feat5': 'محرر + مشاركة',
    'pricing.cta.free': 'ابدأ مجاناً',
    'pricing.cta.basic': 'اختر الأساسي',
    'pricing.cta.premium': 'اختر المميز',
    'pricing.cta.getStarted': 'ابدأ الآن',
    'pricing.cta.choosePro': 'اختر برو',
    'pricing.cta.contact': 'اتصل بالمبيعات',
    'pricing.payPerDesign': 'أو ادفع لكل تصميم:',
    'pricing.ppBoard': 'لكل لوحة أفكار',
    'pricing.ppRedesign': 'لكل إعادة تصميم',
    'pricing.paymentMethods': 'طرق الدفع المقبولة',
    'pricing.instapay': 'إنستاباي',
    'pricing.vodafone': 'فودافون كاش',
    'pricing.paymentNote': 'ارفع صورة إيصال الدفع للتحقق الفوري بالذكاء الاصطناعي.',
    'pricing.faq': 'كيف تعمل عملية الدفع؟',
    'pricing.faqDesc': 'بعد اختيار الخطة، حوّل المبلغ عبر إنستاباي أو فودافون كاش، ثم ارفع صورة الإيصال. سيتحقق ذكاؤنا الاصطناعي منه تلقائياً في دقائق.',

    // ── Testimonials ───────────────────────────────────────────────────────
    'testimonials.badge': 'يحبنا عملاؤنا',
    'testimonials.title': 'محبوب من عشاق التصميم',

    // ── CTA Section ────────────────────────────────────────────────────────
    'cta.title': 'هل أنت مستعد لتحويل مساحتك؟',
    'cta.desc': 'انضم إلى آلاف الأشخاص الذين صمموا منازل أحلامهم مع ظبطلي. لا يلزم بطاقة ائتمان.',
    'cta.button': 'ابدأ التصميم الآن',

    // ── Dashboard ─────────────────────────────────────────────────────────
    'dashboard.welcome': 'مرحباً بعودتك،',
    'dashboard.welcomeAr': 'أهلاً بك',
    'dashboard.subtitle': 'رحلتك الإبداعية مستمرة. ما هي خطة اليوم؟',
    'dashboard.explore': 'استكشف الاتجاهات',
    'dashboard.newMoodboard': 'لوحة أفكار جديدة',
    'dashboard.newRedesign': 'إعادة تصميم جديدة',
    'dashboard.stat.active': 'التصاميم النشطة',
    'dashboard.stat.credits': 'رصيد الذكاء الاصطناعي المتبقي',
    'dashboard.stat.instant': 'إعادة تصميم فورية',
    'dashboard.stat.japandi': 'جرب نمط الياباندي الجديد',
    'dashboard.stat.tryNow': 'جرب الآن',
    'dashboard.stat.thisWeek': '+٣ هذا الأسبوع',
    'dashboard.recent': 'المشاريع الأخيرة',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.startNew': 'ابدأ تصميماً جديداً',
    'dashboard.modifiedAgo': 'تم التعديل',
    'dashboard.footer.privacy': 'سياسة الخصوصية',
    'dashboard.footer.terms': 'شروط الخدمة',
    'dashboard.footer.support': 'مركز الدعم',

    // ── Mood Board Generator ───────────────────────────────────────────────
    'moodboard.title': 'مولّد لوحات الأفكار بالذكاء الاصطناعي',
    'moodboard.subtitle': 'صف رؤيتك ودع ذكاءنا الاصطناعي يصنع الجو المثالي.',
    'moodboard.params': 'معاملات التصميم',
    'moodboard.roomType': 'نوع الغرفة',
    'moodboard.room.living': 'غرفة المعيشة',
    'moodboard.room.bedroom': 'غرفة النوم',
    'moodboard.room.kitchen': 'المطبخ',
    'moodboard.room.bathroom': 'الحمام',
    'moodboard.room.office': 'المكتب',
    'moodboard.style': 'نمط التصميم',
    'moodboard.style.modern': 'سكاندينافي عصري',
    'moodboard.style.midcentury': 'منتصف القرن الحديث',
    'moodboard.style.industrial': 'إندستريال',
    'moodboard.style.boho': 'بوهيمي شيك',
    'moodboard.style.minimal': 'مينيمال زن',
    'moodboard.style.luxury': 'فاخر أرت ديكو',
    'moodboard.dominantColor': 'اللون السائد',
    'moodboard.promptLabel': 'وصف مفصل (اختياري)',
    'moodboard.promptPlaceholder': 'مثال: غرفة معيشة مينيمال مضاءة بضوء الشمس بملمس خشب البلوط وأقمشة كتانية كريمية...',
    'moodboard.generateBtn': 'توليد لوحة الأفكار',
    'moodboard.generating': 'جاري التوليد...',
    'moodboard.mainConcept': 'المفهوم الرئيسي',
    'moodboard.palette': 'لوحة الألوان المولّدة بالذكاء الاصطناعي',
    'moodboard.materials': 'مكتبة المواد',
    'moodboard.exportPdf': 'تصدير PDF',
    'moodboard.shareLink': 'رابط المشاركة',
    'moodboard.saveToFav': 'حفظ في المفضلة',
    'moodboard.saveDashboard': 'حفظ في لوحة التحكم',

    // ── Room Redesign ──────────────────────────────────────────────────────
    'redesign.title': 'إعادة تصميم الغرفة بالذكاء الاصطناعي',
    'redesign.subtitle': 'ارفع صورة مساحتك الحالية ودع ذكاءنا الاصطناعي يحولها في ثوانٍ.',
    'redesign.uploadTitle': 'ارفع صورتك',
    'redesign.uploadLabel': 'اسحب وأفلت صورة غرفتك هنا',
    'redesign.uploadSub': 'يدعم JPG وPNG بحد أقصى ١٠ ميجابايت',
    'redesign.browse': 'تصفح الملفات',
    'redesign.roomType': 'نوع الغرفة',
    'redesign.intensity': 'حدة النمط',
    'redesign.proTip': 'نصيحة احترافية',
    'redesign.proTipText': 'التقط الصور من زاوية الغرفة على مستوى الصدر للحصول على منظور مكاني دقيق.',
    'redesign.preview': 'معاينة تفاعلية',
    'redesign.before': 'قبل',
    'redesign.after': 'بعد',
    'redesign.variations': 'نتائج الذكاء الاصطناعي',
    'redesign.regenerate': 'إعادة التوليد',
    'redesign.useStyle': 'استخدم هذا النمط',
    'redesign.active': 'نشط',
    'redesign.ctaTitle': 'أعجبك هذا الشكل؟',
    'redesign.ctaDesc': 'احصل على قائمة الأثاث من هذا التصميم في بريدك الإلكتروني.',
    'redesign.ctaEmail': 'أدخل بريدك الإلكتروني',
    'redesign.ctaBtn': 'احصل على القائمة',
    'redesign.generating': 'جاري توليد التصميم...',

    // ── Payment ────────────────────────────────────────────────────────────
    'payment.backToPricing': 'العودة للأسعار',
    'payment.planSummary': 'ملخص الخطة',
    'payment.method': 'طريقة الدفع',
    'payment.instapay': 'إنستاباي',
    'payment.vodafone': 'فودافون كاش',
    'payment.instantTransfer': 'تحويل فوري',
    'payment.mobileWallet': 'محفظة فودافون',
    'payment.instructions': 'تعليمات التحويل',
    'payment.step1': 'افتح تطبيق',
    'payment.step1App': '',
    'payment.step2': 'حوّل',
    'payment.step2To': 'إلى الرقم:',
    'payment.step3': 'خذ لقطة شاشة لإيصال التحويل',
    'payment.step4': 'ارفع الصورة أدناه',
    'payment.uploadTitle': 'ارفع صورة الإيصال',
    'payment.uploadLabel': 'اسحب وأفلت صورة الإيصال هنا',
    'payment.uploadSub': 'يدعم JPG وPNG بحد أقصى ١٠ ميجابايت',
    'payment.verifyBtn': 'تحقق من الدفع',
    'payment.processing': 'جاري المعالجة...',
    'payment.verifying': 'جاري التحقق من الدفع...',
    'payment.verifyingDesc': 'يستغرق هذا عادةً أقل من دقيقة',
    'payment.successTitle': 'تم تفعيل الاشتراك!',
    'payment.successDesc': 'تم التحقق من دفعتك بنجاح. يمكنك الآن الاستمتاع بجميع مميزات خطتك.',
    'payment.goToDashboard': 'انتقل إلى لوحة التحكم',
    'payment.failTitle': 'تعذّر التحقق من الدفع',
    'payment.failDesc': 'تأكد من وضوح الصورة وصحة المبلغ. إذا استمرت المشكلة، سيتم مراجعتها يدوياً.',
    'payment.manualTitle': 'قيد المراجعة اليدوية',
    'payment.manualDesc': 'لم نتمكن من التحقق التلقائي من دفعتك. سيقوم فريقنا بالمراجعة خلال ٢٤ ساعة.',

    // ── Settings ───────────────────────────────────────────────────────────
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'أدر حسابك وتفضيلاتك',
    'settings.profile': 'الملف الشخصي',
    'settings.fullName': 'الاسم الكامل',
    'settings.email': 'البريد الإلكتروني',
    'settings.saveChanges': 'حفظ التغييرات',
    'settings.subscription': 'الاشتراك',
    'settings.currentPlan': 'الخطة الحالية',
    'settings.expires': 'تنتهي:',
    'settings.active': 'نشط',
    'settings.upgrade': 'ترقية',
    'settings.usageThisMonth': 'الاستخدام هذا الشهر',
    'settings.moodBoards': 'لوحات الأفكار',
    'settings.redesigns': 'إعادة التصميم',
    'settings.language': 'اللغة',
    'settings.notifications': 'الإشعارات',
    'settings.notif.payment': 'تأكيد الدفع',
    'settings.notif.expiry': 'تحذير انتهاء الاشتراك',
    'settings.notif.tips': 'نصائح التصميم والإلهام',
    'settings.dangerZone': 'المنطقة الخطرة',
    'settings.deleteAccount': 'حذف الحساب',
    'settings.deleteDesc': 'سيتم حذف جميع بياناتك نهائياً ولا يمكن التراجع.',
    'settings.deleteBtn': 'حذف حسابي',

    // ── Editor ─────────────────────────────────────────────────────────────
    'editor.untitled': 'لوحة أفكار بلا عنوان',
    'editor.back': 'رجوع',
    'editor.save': 'حفظ',
    'editor.saved': 'تم الحفظ!',
    'editor.export': 'تصدير',
    'editor.share': 'مشاركة',
    'editor.tools.select': 'تحديد',
    'editor.tools.text': 'نص',
    'editor.tools.image': 'صورة',
    'editor.tools.shape': 'شكل',
    'editor.panel.images': 'صور',
    'editor.panel.colors': 'ألوان',
    'editor.panel.layers': 'طبقات',
    'editor.uploadImage': 'رفع صورة',
    'editor.moodBoardImages': 'صور لوحة الأفكار',
    'editor.palette': 'لوحة الألوان',
    'editor.designColors': 'ألوان التصميم',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  // Falls back to EN key, then returns the raw key if both missing
  const t = (key: string): string =>
    translations[language][key] ?? translations['en'][key] ?? key;

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
